safe: true
lsi: false
pygments: true

baseurl: http://elasticsearchfr.github.io/devoxx-handson-your-log

name: "Devoxx: Hand's on your Logs !"
description: description...
titlebar: Hand's on

gravatar_size: 150

author_ids: [dadoonet, vspiewak]

authors:
  dadoonet:
    display_name: David Pilato
    gravatar: 20049a614b7f6838dc87b4bc39c42079
    email: david@pilato.fr
    web: http://dev.david.pilato.fr
    twitter: dadoonet
    github: dadoonet
    linkedin: dadoonet
    job_title: Technical advocate
    company: Elasticsearch
    bio: 'David Pilato is Technical Advocate at elasticsearch and French spoken language User Group creator. In his free time, he likes talking about elasticsearch in conferences like Devoxx FR and BE, JUGs, Web5, Agile France, Mix-IT or in companies (Brown Bag Lunches).'
  vspiewak:
    display_name: Vincent Spiewak
    gravatar: 5c7908a6f9e7024dcd931b8c08c74a63
    email: vspiewak+github@gmail.com
    web: http://blog.xebia.fr/author/vspiewak
    twitter: vspiewak
    github: vspiewak
    linkedin: vincentspiewak
    job_title: Java / Agile consultant
    company: Xebia
    bio: 'Vincent est un consultant passionné travaillant chez Xebia. Il aime concevoir des projets innovants dans un cadre Agile. Son expérience tourne autour du monde <span class="nowrap">Java / EE</span>, WOA, et de la conduite du changement.'

kibana_url: http://download.elasticsearch.org/kibana/kibana/kibana-latest.zip
kibana_url_title: kibana-latest.zip

logstash_version: 1.2.1
logstash_url: https://download.elasticsearch.org/logstash/logstash/logstash-1.2.1-flatjar.jar
logstash_url_title: logstash-1.2.1-flatjar.jar

loggenerator_url: https://github.com/vspiewak/log-generator
loggenerator_url_title: log-generator.jar

elasticsearch_url: https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.5.tar.gz
elasticsearch_url_title: elasticsearch-0.90.5.tar.gz

geolitecity_url: http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
geolitecity_url_title: GeoLiteCity.dat
